services:
  - type: web
    name: choco-music
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir src main:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: choco-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.10

databases:
  - name: choco-db
    plan: free
